# Generated by Django 5.0.3 on 2024-04-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=200, verbose_name='Decs')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stu_name', models.CharField(max_length=500)),
                ('stu_add', models.CharField(max_length=500)),
                ('stu_aadhar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.department')),
            ],
        ),
    ]
