# Generated by Django 5.0.3 on 2024-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carmodel_fueltypemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='fuel_name',
            field=models.ManyToManyField(to='app.fueltypemodel'),
        ),
    ]
